# Generated by Django 3.2.9 on 2021-12-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211128_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-from_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-from_date']},
        ),
    ]
