# Generated by Django 3.2.9 on 2021-12-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cv_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_projects_completed',
            field=models.IntegerField(default=0),
        ),
    ]
