# Generated by Django 3.2.9 on 2021-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211103_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(default='Researcher', max_length=100),
            preserve_default=False,
        ),
    ]
