# Generated by Django 3.2.9 on 2021-11-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created']},
        ),
    ]
