# Generated by Django 4.0b1 on 2021-10-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isPublished',
            field=models.BooleanField(default=False, verbose_name='Published?'),
        ),
    ]
