# Generated by Django 4.0b1 on 2021-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='nothing'),
            preserve_default=False,
        ),
    ]
