# Generated by Django 3.2.9 on 2021-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211127_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
