# Generated by Django 3.2.9 on 2021-11-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211113_1939'),
        ('blog', '0012_alter_post_category'),
    ]

    operations = [
    ]
